def ingredient_list():
    return [
        {"name": "milk", "properties": ["liquid"]},
        {"name": "whole milk", "properties": ["liquid"]},
        {"name": "vanilla extract", "properties": ["liquid"]},
        {"name": "pure vanilla extract", "properties": ["liquid"]},
        {"name": "eggs", "properties": ["liquid", "undividable"]},
        {"name": "egg white", "properties": ["liquid", "undividable"]},
        {"name": "butter", "properties": ["liquid"]},
        {"name": "unsalted butter", "properties": ["liquid"]},
        {"name": "food coloring", "properties": ["liquid", "coloring"]},
        {"name": "chocolate", "properties": ["liquid"]},
        {"name": "cream", "properties": ["liquid"]},
        {"name": "sour cream", "properties": ["liquid"]},
        {"name": "coffee", "properties": ["liquid"]},
        {"name": "maple syrup", "properties": ["liquid"]},
        {"name": "cream cheese", "properties": ["liquid"]},
        {"name": "fruit strawberry", "properties": ["liquid", "coloring"]},
        {"name": "finely chopped strawberries", "properties": ["liquid", "coloring"]},
        {"name": "fruit apple", "properties": ["liquid", "coloring"]},
        {"name": "fruit carrot", "properties": ["liquid", "coloring"]},
        {"name": "fruit raspberries", "properties": ["liquid", "coloring"]},
        {"name": "fresh lemon juice", "properties": ["liquid", "coloring"]},
        {"name": "sugar", "properties": ["solid"]},
        {"name": "confectioners sugar", "properties": ["solid"]},
        {"name": "brown sugar", "properties": ["solid"]},
        {"name": "granulated sugar", "properties": ["solid"]},
        {"name": "light-brown sugar", "properties": ["solid"]},
        {"name": "flour", "properties": ["solid"]},
        {"name": "all-purpose flour", "properties": ["solid"]},
        {"name": "cake flour", "properties": ["solid"]},
        {"name": "baking powder", "properties": ["solid"]},
        {"name": "baking soda", "properties": ["solid"]},
        {"name": "salt", "properties": ["solid"]},
		{"name": "coarse salt", "properties": ["solid"]},
        {"name": "cocoa", "properties": ["solid"]},
        {"name": "cocoa powder", "properties": ["solid"]},
		{"name": "unsweetened cocoa powder", "properties": ["solid"]},
        {"name": "walnuts", "properties": ["solid"]},
        {"name": "almonds", "properties": ["solid"]},
        {"name": "freshly grated lemon zest", "properties": ["solid"]},
        {"name": "chocolate chips", "properties": ["solid"]},
        {"name": "semisweet milk chocolate chips", "properties": ["solid"]},

    ]
