def ingredient_list():
    return [
        {"name": "milk", "properties": ["liquid"]},
        {"name": "vanille extract", "properties": ["liquid"]},
        {"name": "eggs", "properties": ["liquid", "undividable"]},
        {"name": "butter", "properties": ["liquid"]},
        {"name": "food coloring", "properties": ["liquid", "coloring"]},
        {"name": "chocolate", "properties": ["liquid"]},
        {"name": "cream", "properties": ["liquid"]},
        {"name": "coffee", "properties": ["liquid"]},
        {"name": "maple syrup", "properties": ["liquid"]},
        {"name": "cream cheese", "properties": ["liquid"]},
        {"name": "fruit strawberry", "properties": ["liquid", "coloring"]},
        {"name": "fruit apple", "properties": ["liquid", "coloring"]},
        {"name": "fruit carrot", "properties": ["liquid", "coloring"]},
        {"name": "fruit raspberries", "properties": ["liquid", "coloring"]},
        {"name": "sugar", "properties": ["solid"]},
        {"name": "brown sugar", "properties": ["solid"]},
        {"name": "flour", "properties": ["solid"]},
        {"name": "baking powder", "properties": ["solid"]},
        {"name": "salt", "properties": ["solid"]},
        {"name": "cocoa", "properties": ["solid"]},
        {"name": "walnuts", "properties": ["solid"]},
        {"name": "almonds", "properties": ["solid"]},
        {"name": "chocolate chips", "properties": ["solid"]},
    ]
